---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ./svm-latex-ms.tex
title: "Behavioral Economics"

author:
- name: Aaron Austin
  affiliation: Huntsman College of Business
abstract: "This paper acknowledges the writings of Buchanan and dives even deeper into the meaning and implications of what it means to study "the theory of markets". At one point, preference and utility were very arbitrary and vague ideas just as behavior is now. These ideas were transformed into specific formulas that, with a good degree of accuracy, could predict specific individual’s decisions. With the advent of technology, we are better able to gather, compute, and analyze this data. This paper proposes that future analysis will take into consideration what Buchanan terms “theory of choice” and will be able to transform them into imperial computational data that can then be analyzed. By doing so, future analysis of  the “theory of choice” evolves into just another technological problem to compute
keywords: "Python, Monte Carlo, simulation, arbitrage"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: ./master.bib
biblio-style: apsr
---


>  

 Introduction
 


## Subsection 1: : Buchanan and his ideologies

• Outline what Buchanan’s main point is. 
James Buchanan argues that the economist should focus in "the theory of markets", instead of the "theory of resource allocation" or "theory of choice, the central idea of the discipline should be the cooperative association of individuals (behaviour of exchange, trade or agreement). He states,”Economistst should concentrate their attention on a particular form of human activity and upon the various institutional arrangements that arise as a result of this form of activity.

• What does Buchanan mean by the word catallatics? 
He uses it interchangeably with the word symbiotic. Symbiotics is the study of the association between dissimilar organisms and the connotation of the term is that the  association is mutually beneficial to all parties. 

• According to Buchanan what do most economists do? 
He says that most economists are wholly concerned with the allocation of scarce resources among competing ends or uses.

• What does he think they should do differently?
They need to quit concerning themselves with allocation problems as it has been defined in the traditional way. They need to recognize them for what they truly are: contributions to applied mathematics, to managerial science but not to the chosen subject field which is called economics. Understand that if the utility function of the choosing agent is fully defined in advance, then the choice becomes purely mechanical. He states,” if I know what I want a  computer can make all of my choices for me. If I do not know what I want no possible computer can derive my utility function since it does not really exist.” He then urges that economists study the unique symbiotic aspects of behavior that arise from exchange or trade. He urges that he wants them to concentrate on “exchange” rather than on choice.




This paper acknowledges the writings of Buchanan and dives even deeper into the meaning and implications of what it means to study "the theory of markets". At one point, preference and utility were very arbitrary and vague ideas just as behavior is now. These ideas were transformed into specific formulas that, with a good degree of accuracy, could predict specific individual’s decisions. With the advent of technology, we are better able to gather, compute, and analyze this data. This paper proposes that future analysis will take into consideration what Buchanan terms “theory of choice” and will be able to transform them into imperial computational data that can then be analyzed. By doing so, future analysis of  the “theory of choice” evolves into just another technological problem to compute.



##Subsection 2 :It's not about the nail-How economists rush to solve short term problems

##Subsection 3 : The quantification of utility

##Subsection 4: Technology and how it helps economists

# Middle Section

##Subsection 5: Quantification of behavior: The next evolutionary step in economics 

##Subsection 6: Implications of behavioral quantification

##subsection 7: Economics: The crafting of tools for mathmatitions to weild

# Summary and Conclusion



<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->

